import MobxProvider from '@/store/context';
// import './globals.css';
import '../styles/index.css';
import MainLayout from '@/layouts/MainLayout/MainLayout';
// import { Inter } from 'next/font/google';

// const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

// TODO: Я что-то в прошлых проектах таких фокусов с мобиксом не помню, он там и без них вроде прекрасно работал - вспомни как там ты делал

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      {/* <body className={inter.className}> */}
      <body>
        <MobxProvider>
          <MainLayout>{children}</MainLayout>
        </MobxProvider>
      </body>
    </html>
  );
}
